services:
  postgres:
    image: postgres
    container_name: petshop-appointments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petshop-appointments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data

volumes:
    pgdata: